This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./main_long.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file main_long.acn....done (269 entries accepted, 0 rejected).
Sorting entries.....done (2219 comparisons).
Generating output file main_long.acr....done (169 lines written, 0 warnings).
Output written in main_long.acr.
Transcript written in main_long.alg.
